package usecase

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/mandarnilange/corvee/internal/domain"
)

// InitInput is the request payload for Init. The caller (typically
// internal/cli) is responsible for resolving TasksDir from the
// project root, AgentID from the --agent flag with $CORVEE_AGENT_ID and
// $USER fallbacks, etc.
type InitInput struct {
	// TasksDir is the absolute or working-dir-relative path to the
	// .tasks/ directory that Init bootstraps. Init creates the
	// directory tree under it (items/, events/, operations/, locks/,
	// hooks/) and writes workspace.json + local.json + .gitignore.
	TasksDir string
	// WorkspaceName is the human-readable workspace label (required).
	WorkspaceName string
	// DefaultProject is the optional default project code, prepended
	// to relative IDs in CLI flags. Empty string means "no default".
	DefaultProject string
	// AgentID is the per-VM agent identity to seed local.json with.
	// Empty falls back to $USER.
	AgentID string
	// Force, when true, allows Init to re-run on an existing
	// workspace. workspace.json is rewritten; local.json is preserved
	// so the per-VM identity isn't clobbered.
	Force bool
}

// InitOutput is the response payload describing where the bootstrapped
// configs landed.
type InitOutput struct {
	// WorkspacePath is the absolute path of workspace.json.
	WorkspacePath string `json:"workspace_path"`
	// LocalPath is the absolute path of local.json.
	LocalPath string `json:"local_path"`
}

// gitignoreBody is the canonical .tasks/.gitignore content per spec
// §3 / SQ-003: index.json (cache), operations/ (per-VM WAL), locks/
// (POSIX locks), local.json (per-VM identity) are all gitignored.
const gitignoreBody = "# Generated by `corvee init`. Do not edit by hand.\n" +
	"index.json\n" +
	"operations/\n" +
	"locks/\n" +
	"local.json\n"

// Init bootstraps a workspace at TasksDir per spec §3 and §S10. The
// directory tree is created idempotently; workspace.json is always
// written; local.json is preserved when Force re-init runs over an
// existing workspace so the per-VM agent identity stays intact.
func Init(_ context.Context, d Deps, in InitInput) (InitOutput, error) {
	if in.TasksDir == "" {
		return InitOutput{}, fmt.Errorf("init: tasks_dir is required: %w", domain.ErrUsage)
	}
	if in.WorkspaceName == "" {
		return InitOutput{}, fmt.Errorf("init: workspace_name is required: %w", domain.ErrUsage)
	}

	wsExists, err := d.Workspace.Exists()
	if err != nil {
		return InitOutput{}, fmt.Errorf("init: probe workspace: %w", err)
	}
	if wsExists && !in.Force {
		return InitOutput{}, fmt.Errorf("init: workspace already exists at %s; pass --force to re-init: %w",
			in.TasksDir, domain.ErrUsage)
	}

	for _, sub := range []string{"items", "events", "operations", "locks", "hooks"} {
		path := filepath.Join(in.TasksDir, sub)
		if mkErr := os.MkdirAll(path, 0o755); mkErr != nil {
			return InitOutput{}, fmt.Errorf("init: mkdir %s: %w", path, mkErr)
		}
		// Phase 7: ensure git-trackable so an executor clone has the
		// full layout even before any items/events land. The .gitignore
		// keeps index.json/operations/locks gitignored — committing a
		// .gitkeep here is harmless because git matches by filename.
		if sub == "items" || sub == "events" || sub == "hooks" {
			if writeErr := os.WriteFile(filepath.Join(path, ".gitkeep"), []byte(""), 0o600); writeErr != nil {
				return InitOutput{}, fmt.Errorf("init: write .gitkeep in %s: %w", path, writeErr)
			}
		}
	}

	if writeErr := os.WriteFile(filepath.Join(in.TasksDir, ".gitignore"), []byte(gitignoreBody), 0o600); writeErr != nil {
		return InitOutput{}, fmt.Errorf("init: write .gitignore: %w", writeErr)
	}

	ws := domain.Workspace{
		SchemaVersion:            domain.CurrentSchemaVersion,
		WorkspaceName:            in.WorkspaceName,
		DefaultProject:           in.DefaultProject,
		ClaimTTLMinutes:          60,
		HeartbeatIntervalMinutes: 30,
		CriticalPath:             []string{},
		Git:                      domain.GitConfig{AutoCommit: false, AutoSyncSeconds: nil},
	}
	if saveErr := d.Workspace.Save(ws); saveErr != nil {
		return InitOutput{}, fmt.Errorf("init: save workspace: %w", saveErr)
	}

	localExists, err := d.Local.Exists()
	if err != nil {
		return InitOutput{}, fmt.Errorf("init: probe local: %w", err)
	}
	if !localExists {
		agent := in.AgentID
		if agent == "" {
			agent = os.Getenv("USER")
		}
		local := domain.Local{
			DefaultAgent: agent,
			AgentRole:    domain.RoleHuman,
		}
		if saveErr := d.Local.Save(local); saveErr != nil {
			return InitOutput{}, fmt.Errorf("init: save local: %w", saveErr)
		}
	}

	return InitOutput{
		WorkspacePath: filepath.Join(in.TasksDir, "workspace.json"),
		LocalPath:     filepath.Join(in.TasksDir, "local.json"),
	}, nil
}
